### ISSUE TITLE
[BUG]: The issuing_date type in the openapi doesn't match with the return type

### ISSUE THREAD

**Issue by algra4** [getlago/lago-openapi#229]
**Describe the bug**
I generated the java client based on your openapi. 
But when I try to get the current usage for a customer, I received this error
Stacktrace:

```code
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.OffsetDateTime` from String "2024-05-31": Failed to deserialize java.time.OffsetDateTime: (java.time.format.DateTimeParseException) Text '2024-05-31' could not be parsed at index 10
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 111] (through reference chain: org.getlago.client.model.CustomerUsage["customer_usage"]->org.getlago.client.model.CustomerUsageObject["issuing_date"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DeserializerBase._handleDateTimeException(JSR310DeserializerBase.java:176) ~[jackson-datatype-jsr310-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer._fromString(InstantDeserializer.java:301) ~[jackson-datatype-jsr310-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:211) ~[jackson-datatype-jsr310-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:52) ~[jackson-datatype-jsr310-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:392) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:392) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:395) ~[spring-web-6.1.4.jar!/:6.1.4]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:354) ~[spring-web-6.1.4.jar!/:6.1.4]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:103) ~[spring-web-6.1.4.jar!/:6.1.4]
        ... 155 more
Caused by: java.time.format.DateTimeParseException: Text '2024-05-31' could not be parsed at index 10
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(Unknown Source) ~[?:?]
        at java.base/java.time.format.DateTimeFormatter.parse(Unknown Source) ~[?:?]
        at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer._fromString(InstantDeserializer.java:295) ~[jackson-datatype-jsr310-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:211) ~[jackson-datatype-jsr310-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:52) ~[jackson-datatype-jsr310-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:392) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:392) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481) ~[jackson-databind-2.15.4.jar!/:2.15.4]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:395) ~[spring-web-6.1.4.jar!/:6.1.4]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:354) ~[spring-web-6.1.4.jar!/:6.1.4]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:103) ~[spring-web-6.1.4.jar!/:6.1.4]
```

The problem is the **issuing_date** [type](https://github.com/getlago/lago-openapi/blob/e0b691455e2376ae5b1acee079b68aa6ead712fe/src/schemas/CustomerUsageObject.yaml#L23) (and the [exemple](https://github.com/getlago/lago-openapi/blob/e0b691455e2376ae5b1acee079b68aa6ead712fe/src/schemas/CustomerUsageObject.yaml#L25)), the value is `date-time`but it should be `'date`to match with the response of your api.

**To Reproduce**
Get the current usage of a customer:

Example of response: 

```json
    "to_datetime": "2024-05-31T23:59:59Z",
    "issuing_date": "2024-05-31",
    "currency": "EUR",
```

**Expected behavior**
Modify the type and example in the `CustomerUsageObject` 

**Screenshots**
N/A

**Support**
 - Version [e.g. 22]: 1.3.0

**Additional context**
N/A

**Comment by rsempe** [comment]
Thanks @algra4, it's fixed on this PR: https://github.com/getlago/lago-openapi/pull/230
